### ISSUE TITLE
Tag selection doesn't seem to respect g:targets_seekRanges

### ISSUE THREAD

**Issue by alireza** [wellle/targets.vim#136]
Repro details:

" in .vimrc -- Notice there is no `rr`
```
let g:targets_seekRanges = 'cr cb cB lc ac Ac lr lb ar ab lB Ar aB Ab AB'
```

" input.html - cursor position indicated with ||

```
<!DOCTYPE html>
<html>
<body>
  ||  <div id="root">Hello</div>
</body>
</html>
```

Pressing `vit` selects `Hello`, but it should select `    <div id="root">Hello</div>`.

```
:versoin
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 11 2014 04:03:29)
MacOS X (unix) version
Included patches: 1-488
Compiled by Homebrew
...
```

**Comment by wellle** [comment]
@alireza: Thanks for reporting this. I'll try to reproduce and fix this next weekend. I believe tag objects currently don't consider the seek ranges setting, but they should :+1:

**Comment by wellle** [comment]
Actually it works for me as expected. After putting that line into my `.vimrc`, typing `vit` on `||` in your example does select `  ||  <div id="root">Hello</div>`.

Without that setting it selects `Hello`.

In Vim, can you run this ex command:
```vim
:echo g:targets_seekRanges
```
and check that it actually outputs `cr cb cB lc ac Ac lr lb ar ab lB Ar aB Ab AB` at the bottom?

Otherwise your setting doesn't seem to be loaded.

Also, can you check what version of targets.vim you're using by checking the git log in the targets.vim plugin directory? Or just update to make sure you're on the latest version and try again?

**Comment by wellle** [comment]
@alireza: Please reopen if this is still an issue. Thanks!
