### ISSUE TITLE
[question] Insert another argument

### ISSUE THREAD

**Issue by balta2ar** [wellle/targets.vim#146]
Hello. Sorry if this question has nothing to do with targets, but I thought it might. Say, I'm standing on this line:
``` python
def __init__(self, na|me, path)
```
What I want is to quickly go to insert mode and append one more argument. Say, I could press "ana" (Append after Next Argument) and I would get:
``` python
def __init__(self, name, path, |)
```
OR
``` python
def __init__(self, name, path|)
```

Is this possible and (if yes) how to do that?

**Comment by wellle** [comment]
@balta2ar: Actually that has come up before, and I created a gist with a very simple mapping to accomplish something like what you describe: https://gist.github.com/wellle/9289224

With that in your vimrc, with the setup you describe, you could type
```
\aina, test
```
to **append after** (`\a`) the **next inner argument** (`ina`) the text `, test`, resulting in this:
```python
def __init__(self, name, path, test)
```
But note that this has been done by adding a new **operator** (`\a`) to operate on existing **text objects** (`ina`). Since targets.vim is about text objects (not operators), this seems out of scope of **this** plugin.

**Comment by balta2ar** [comment]
@wellle Thank you very much! Your receipt is exactly what I wanted, now I just need to live with it for a while and get it into my muscle memory. :muscle:
