### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by balta2ar** [wellle/targets.vim#156]
Here is a friendly reminder about the outdated documentation (after discussion in this commit: https://github.com/wellle/targets.vim/commit/1d39837aceadfdeaa4235ba0035b6153863b8c15).
This section (https://github.com/wellle/targets.vim/blob/master/doc/targets.txt#L633) is missing "`c`: on cursor position". And perhaps https://github.com/wellle/targets.vim/blob/master/cheatsheet.md#customize-seeking is missing jumpRanges, but maybe it's not included intentionally, I'm not sure.

**Comment by wellle** [comment]
@balta2ar: Thanks!

`jumpRanges` is documented directly in the [README](https://github.com/wellle/targets.vim#gtargets_jumpranges). I moved the details about `seekRanges` documentation out into the Cheatsheet and linked it from the README because that's quite verbose and a bit obscure.

I'll fix the missing `c` docs.
