### ISSUE TITLE
Argument Text Object Newlines

### ISSUE THREAD

**Issue by jrpotter** [wellle/targets.vim#163]
Deleting an argument target does not seem to work as expected depending on newline spacing. For instance, placing the cursor in the first argument of the following definition and pressing `daa` (or any command with an argument text object) will operate on the second. Here is an example:

```cpp
void TestClass::Function(
    int arg1, bool arg2) {

}
```

If the cursor is in `arg1` and `daa` is pressed, it is `arg2` that is deleted.

**Comment by wellle** [comment]
That's expected behavior because by default targets within the cursor line are preferred over targets that are not contained in the current line. If you don't like that you can adjust `g:targets_seekRanges` to always prefer targets around the cursor for example. Check the readme (and cheatsheet) for examples and explanations.

On the other hand, the way you format your code does seem unusual to me. If you put each argument  in the same line or each argument on its own line it should work fine.

**Comment by jrpotter** [comment]
Ah, thanks for the update. Work forces formatting to be within 80 characters a line so some formatting is forcibly weird when function declarations get a bit large hehe. I appreciate the help.

**Comment by wellle** [comment]
Yeah I also like to split long lines by breaking up argument lists. But then I always just put every argument on its own line. Maybe that works for you too.
