### ISSUE TITLE
BUG about  ia  mapping

### ISSUE THREAD

**Issue by huaihuaiVV** [wellle/targets.vim#167]
```c
test((void *)var,
    var2, (void*)var3,
    (void*)var4)
```

when i use via to select var4,
it will select void* , not as expected . ...

Thanks for your plugin  👍

**Comment by Wagk** [comment]
I have a similar problem where (with `*` as the caret) pressing `via`
```
        src_path = Path(con*fig['dataset']
                        ).joinpath(file).resolve()
```
will select `'dataset'` instead of `config['dataset']`

This issue goes away when the statement is formatted to look like 
```
        src_path = Path(con*fig['dataset']).joinpath(file).resolve()
```

In that case `via` works normally

**Comment by wellle** [comment]
@huaihuaiVV @Wagk: Both of your cases work as expected.

@huaihuaiVV: If you put the cursor on the outer closing `)` it should work.
@Wagk: If you put the cursor on the first opening `(` it should work.

The reason is that by default targets are preferred that are fully contained in the cursor line. In your cases that is `(void*)` and `['dataset']` respectively (both of which look like arguments to targets.vim).

In these cases you can force it to use the multiline target if you position the cursor on one of the target delimitiers (`(` and `)` here).

You can also change the seeking behavior to always prefer targets around the cursor over distant targets in the cursor line, like this:
```vim
let g:targets_seekRanges = 'cr cb cB lc ac Ac lr lb ar ab lB Ar aB Ab AB rr ll rb al rB Al bb aa bB Aa BB AA'
```

I added this example to the docs in #171. In those docs you can also find details about what that means and how to customize it even more.

Please let me know if that works for you and close the issue if so 👍

**Comment by wellle** [comment]
Please reopen if those settings didn't make it work for you.
