### ISSUE TITLE
Questions on `N` `L`

### ISSUE THREAD

**Issue by nkgm** [wellle/targets.vim#174]
Before I start, congrats on this amazing plugin 😄 

Reading the extensive docs I found it's not quite clear what `N` and `L` are used for. These seem to be relevant for the following two categories of text objects: 

**Quote Text Objects**
* In [cheatsheet.md](https://github.com/wellle/targets.vim/blob/master/cheatsheet.md#quote-mappings): only `L` listed as available in mappings, but not listed at all in the chart.
* No `omaps` listed for `:verbose map iL` etc (the actual output of this command in fact shows `N` `L` are only used with separator text objects).
* The README says they're meant to jump the pseudo quote (assuming that in `[ "a", "b"]` the pseudo quote is the `", "` in between) but I believe the default `in"` behavior will intelligently do what `N` implies.

**Separator Text Objects**
Here `N` `L` behave identical to `2n` `2l`. Docs say:
> Use uppercase `N` and `L` to jump from within one pair of separators into the next distinct pair, instead of into the adjacent one.

Wondering why it's so important to jump straight to a non-adjacent pair. Wouldn't it be tidier keeping things simple with `2n` `2l`?

**Comment by wellle** [comment]
@nkgm: Hey, thanks for bringing up this topic. As you noticed there have been some changes along the way, so here's some background:

Initially the quote targets weren't "smart", they worked similar to the buildin text objects. That means if you're inside a quote (like `a` in your example) and you want to operate on the next actual quote (`b`) you'd need to say `c2in"` to skip the pseudo quote `,`. In order to make that a bit more convenient I added `N` and `L` as shortcuts for that. While at it I thought why not add it for separator objects as well. Looking back I don't remember actually using that for separators ever though.

Then later the quotes got smart and `N` and `L` were no longer needed and got removed. #153

Interestingly it looks like the cheatsheet was always inconsistent about the quote mapping, listing `n`, `l` and `L`, but never `N`, I shall fix that 👍 

I agree, at this point it seems weird to have them for separator objects only. So I guess I might at least remove it from the docs to avoid such confusion. 

I might also remove the functionality as I actually don't expect anyone to actually use that for separators.

Unfortunately they are also kinda hinted at in the name of the option `g:targets_nlNL`. And renaming the option would be a breaking change. So I'll probably spare that for now. Or maybe consider aliasing it to have a name without `NL` while still accepting the old one.

Thanks you for this 👍
