### ISSUE TITLE
Issue about '  vi"  ' or double enclosed problem.

### ISSUE THREAD

**Issue by ar1xwe** [wellle/targets.vim#185]
e.g.
```
...
, SD "\Program Files (x86)\NVIDIA Corporation\NvTelemetry\"
, "NvTelemetryContainer.exe")
...
```

Do '  vi" ', vim will select

```
"\Program Files (x86)\NVIDIA Corporation\NvTelemetry\"
, "
```

instead of

`"\Program Files (x86)\NVIDIA Corporation\NvTelemetry\"`

because this string is enclosed by '\'(backslash) too, how to fix this issue?

**Comment by wellle** [comment]
@ar1xwe: This is not an issue of this plugin, but how Vim itself handles quotes. If you join your lines
```
, SD "\Program Files (x86)\NVIDIA Corporation\NvTelemetry\", "NvTelemetryContainer.exe")
```
and then start Vim without plugins (`vim -u NONE`) and type `va"` you'll see that the issue persists.

It's because the second `"` looks escaped because it's directly behind a backslash (which isn't escaped itself). Usually backslashes have such a special meaning and it looks like your case is very special. I don't think I want to try to recognize such cases, so this is probably not going to be "fixed".

I'm curious, in what files don't you need to escape backslashes?

**Comment by ar1xwe** [comment]
@wellle 
Thank you for the explanation.

> **I'm curious, in what files don't you need to escape backslashes?**

Good point !
