### ISSUE TITLE
`g:targets_seekRanges` not being respected

### ISSUE THREAD

**Issue by jearbear** [wellle/targets.vim#227]
Couldn't find anything around this, I'm honestly very confused as to what's going on. It seems that no matter what I set `g:targets_seekRanges` to, the seeking behavior remains the same. I made sure to update to master and am using neovim version 0.3.4.

To verify this, I set `let g:targets_seekRanges = 'cc'` in my config. I would expect this to essentially disable seeking, but after quitting and starting vim, doing something like `cib` will still seek to the next pair several lines below my cursor. I've made sure to disable other plugins and settings and did `:echo g:targets_seekRanges` to confirm that it's set to a correct value.

Any help would be greatly appreciated! Is there some kind of debug mode that I can look into to provide more information?

**Comment by jearbear** [comment]
I stripped my `init.vim` to the bare minimum if that helps:
```
call plug#begin('~/.config/nvim/plugged')
Plug 'wellle/targets.vim'
call plug#end()

let g:targets_seekRanges = 'cc'
```

**Comment by wellle** [comment]
Thank you, I will look into this soon.

**Comment by wellle** [comment]
@jearbear: Thanks, it should be fixed by #228. The old behaviour was basically only changing the ranking of the targets, but it wasn't possible to exclude targets by not including their range in the seek ranges setting. But it definitely makes sense to allow that, and that's also how the documentation reads.

Please check again and let me know if it works now. 🙏

**Comment by jearbear** [comment]
Yup, works like a charm now! Thanks so much for fixing this so quickly :)

**Comment by wellle** [comment]
Thank you! ❤️
