### ISSUE TITLE
Disabling mappings

### ISSUE THREAD

**Issue by blasco** [wellle/targets.vim#241]
I've seen in the documentation that I can extend the mappings, but is it possible to remove some of them? 
'b' collides with other text objects that I'm using and I would like to use it as 'br'. I've tried to extend the mappings doing this, as in the example of the documentation:

```
autocmd User targets#mappings#user call targets#mappings#extend({
    \ '(': {'pair': [{'o': '(', 'c': ')'}]},
    \ ')': {'pair': [{'o': '(', 'c': ')'}]},
    \ '{': {'pair': [{'o': '{', 'c': '}'}]},
    \ '}': {'pair': [{'o': '{', 'c': '}'}]},
    \ 'B': {'pair': [{'o': '{', 'c': '}'}]},
    \ '[': {'pair': [{'o': '[', 'c': ']'}]},
    \ ']': {'pair': [{'o': '[', 'c': ']'}]},
    \ '<': {'pair': [{'o': '<', 'c': '>'}]},
    \ '>': {'pair': [{'o': '<', 'c': '>'}]},
    \ '"': {'quote': [{'d': '"'}]},
    \ "'": {'quote': [{'d': "'"}]},
    \ '`': {'quote': [{'d': '`'}]},
    \ ',': {'separator': [{'d': ','}]},
    \ '.': {'separator': [{'d': '.'}]},
    \ ';': {'separator': [{'d': ';'}]},
    \ ':': {'separator': [{'d': ':'}]},
    \ '+': {'separator': [{'d': '+'}]},
    \ '-': {'separator': [{'d': '-'}]},
    \ '=': {'separator': [{'d': '='}]},
    \ '~': {'separator': [{'d': '~'}]},
    \ '_': {'separator': [{'d': '_'}]},
    \ '*': {'separator': [{'d': '*'}]},
    \ '#': {'separator': [{'d': '#'}]},
    \ '/': {'separator': [{'d': '/'}]},
    \ '\': {'separator': [{'d': '\'}]},
    \ '|': {'separator': [{'d': '|'}]},
    \ '&': {'separator': [{'d': '&'}]},
    \ '$': {'separator': [{'d': '$'}]},
    \ 't': {'tag': [{}]},
    \ 'a': {'argument': [{'o': '[([]', 'c': '[])]', 's': ','}]},
    \ 'br': {'pair': [{'o':'(', 'c':')'}, {'o':'[', 'c':']'}, {'o':'{', 'c':'}'}]},
    \ 'q': {'quote': [{'d':"'"}, {'d':'"'}, {'d':'`'}]},
    \ })
```

So I've changed  `\ 'br': {'pair': [{'o':'(', 'c':')'}, {'o':'[', 'c':']'}, {'o':'{', 'c':'}'}]},`. Nevertheless this doesn't unmap 'b'. Any suggestion?

**Comment by wellle** [comment]
Yes, see https://github.com/wellle/targets.vim#targetsmappingsextend

>If you want to remove a mapping from the defaults, just set it to an empty list of sources:
>
>```vim
>autocmd User targets#mappings#user call targets#mappings#extend({
>    \ 'q': {},
>    \ })
>```

And you don't need to include the ones which you don't want to change, so in your case keys `br` and `b` should be enough. Do it work with `br` though? I think only single character triggers are currently supported.

**Comment by wellle** [comment]
Please reopen if this didn't work for you :v:

**Comment by blasco** [comment]
Sorry for the delay, quite busy lately. It doesn't work with `br` and neither does with `b`. This is what I currently have:

```
autocmd User targets#mappings#user call targets#mappings#extend({
    \ 'b': {},
    \ 'br': {'pair': [{'o':'(', 'c':')'}, {'o':'[', 'c':']'}, {'o':'{', 'c':'}'}]},
    \ })
```

But `cib` plus waiting works, it changes in the braces. `cibr` inserts an `r` character.

**Comment by blasco** [comment]
I cannot reopen the issue by the way as I didn't close it ([you can only re-open issues you closed your self apparently](https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github))

**Comment by wellle** [comment]
Thanks for your response!

It's expected that `cib` still somewhat works, as it's falling back to vanilla Vim behavior. But for example now `cib` shouldn't seek anymore, so if you do it outside of a block it won't operate on it. Can you confirm that? (Another way to try it is do it within `[]` brackets. The targets.vim behavior changes in those as well, vanilla Vim does not.)
Because then original issue of disabling a mapping would be solved, as the above mentioned way should allow you to disable a target mapping (which makes it fall back to other mappings or Vim behavior)

Then the other part of your issue is using a multi character trigger `br`. Which currently isn't supported. As you noticed, it basically runs `cib` and then inputs `r`, which replaces the block. This does seem to be a useful addition to targets.vim, so please feel free to open a separate issue about that 👍
