### ISSUE TITLE
argument textobjects on braces

### ISSUE THREAD

**Issue by unphased** [wellle/targets.vim#254]
When working with javascript something like this: 

    const opts = { type: "select", ...enqOpts };

I'd like a quick way to e.g. delete the entire `type: "select",` part, and if the brackets were parens, this would work fine.

It looks possible by extending, I will report back if I can make it work.

**Comment by unphased** [comment]
I'm thoroughly perplexed by the meaning of `[]` in: 

    'a': {'argument': [{'o': '[([]', 'c': '[])]', 's': ','}]},

**Comment by unphased** [comment]
Furthermore, upon trying 

     autocmd User targets#mappings#user call targets#mappings#extend({
			\ 'a': {'argument': [{'o': '{[([]', 'c': '[])]}', 's': ','}]},
			\ })

All this did was render the `a` functionality completely inoperable.

**Comment by wellle** [comment]
@unphased: Thanks for opening this issue. I can see how this is confusing. The `argument` settings `o` and `c` are actually regexes, so for example `[{[]` means `{` or `[`. It's important to keep `[` and `]` as the first and last character so this is a valid regex. And in order to include a `[` or `]` within the range it needs to be the last or first character respectively within the surrounding `[]`.

Please try this version:
```vim
autocmd User targets#mappings#user call targets#mappings#extend({
		\ 'a': {'argument': [{'o': '[{([]', 'c': '[])}]', 's': ','}]},
		\ })
```

We used to have this better documented, but I removed that part when refactoring the settings. See https://github.com/wellle/targets.vim/tree/v0.4.6#gtargets_argopening-and-gtargets_argclosing

I guess we should bring back that documentation, it even included your use case as an example. So let me know if the suggestion above works for you, but please keep this issue open as a reminder to improve the documentation.

**Comment by unphased** [comment]
Ah, I wish I thought to treat them as regexes. Thanks! Will try that out.

**Comment by eight04** [comment]
Does #267 fix this?

**Comment by unphased** [comment]
> Does #267 fix this?

Yup
